### ISSUE TITLE
Wishlist: Display Folder Path at Top

### ISSUE THREAD

**Issue by Matir** [dom111/webdav-js#100]
It would be nice to have a `Index of /` or similar line at the top to tell you what your current working directory is.  I've tried to hack around it but I don't find any event that's fired on the navigation.

**Comment by dom111** [comment]
Hey, thanks for the feedback!

This is displayed in the URL and page title at the moment, but agree it would be on screen too. I'll take a look at this in my next batch of changes.

Thanks!

Dom

**Comment by dom111** [comment]
This is released in 2.2.0!
