### ISSUE TITLE
Unable to create directory that contains spaces

### ISSUE THREAD

**Issue by dom111** [dom111/webdav-js#19]

**Comment by dom111** [comment]
This is actually warned in the code directly, I can't remember why I added that feature (it was a while ago) so I'll experiment with adding that in and get it tested.

**Comment by dom111** [comment]
Hey @nielll,

Not sure if you'll get this ping, but I've updated the project to handle creating a directory with spaces in the name now. I've tested it locally with success, but I'd love some feedback if you have the time!

Thanks,

Dom

**Comment by nielll** [comment]
I tested your changes and I'm happy with it. Just the alert window contains %20 characters for spaces, but that doesn't bother me. Thx

**Comment by nielll** [comment]
@dom111 It is a little bit annoying that, when I rename a file which contains spaces the filename is written inside the input field with '%20'. So I need to first delete %20 and enter spaces, otherwise I get the alert back that the filename is bad. If you could insert spaces instead of '%20' would make it easier.

**Comment by dom111** [comment]
Hey @nielll,

I'm not seeing that behaviour my end... Are you using the CDN URLs? It might be that they are out of date! Using the docker instance built from `test/` shows this correctly. I am however working on a commit to ensure `file.title` is always used in place of `file.name` in all notifications and within the prefilled text in the `prompt`.

I'll push this out shortly.

Thanks!

Dom

**Comment by nielll** [comment]
I'm using the boorkmarklet from the README.md. Those are the right cdn's? As I saw they are out of date indeed, how do I need to proceed?

**Comment by dom111** [comment]
Ok, that makes sense.

It should be possible to test using:

    javascript:!function(){var t;t=["https://file.titlerawgit.com/noelboss/featherlight/1.7.1/release/featherlight.min.js","https://file.titlerawgit.com/google/code-prettify/master/loader/run_prettify.js?autorun=false","https://file.titlerawgit.com/notifyjs/notifyjs/master/dist/notify.js","https://file.titlerawgit.com/noelboss/featherlight/1.7.1/release/featherlight.min.css","https://file.titlerawgit.com/dom111/webdav-js/master/assets/css/style-min.css","https://file.titlerawgit.com/dom111/webdav-js/master/src/webdav-min.js"];var e,s=document.getElementsByTagName("head")[0],n=function(t,e){var a=document.createElement("script");a.src=t,a.type="text/javascript",e&&(a.onload=e),s.appendChild(a)};n("https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js",function(){t.forEach(function(t){var e,a;t.match(/css$/)?(e=t,(a=document.createElement("link")).href=e,a.rel="stylesheet",s.appendChild(a)):n(t)})}),(e=document.createElement("meta")).name="viewport",e.content="width=device-width, initial-scale=1",s.appendChild(e)}();

**Comment by dom111** [comment]
Yeah, so I did a find/replace (badly!) so it shouldn't have had `file.title`, oops!

But glad you found a solution!

I need to update the bookmarklet and Apache CDN examples based on your info too. Thank you! I'll raise a separate issue for that.

In the meantime, please confirm if you're seeing everything working as expected and if so, please close this!

Thanks for your time!

**Comment by nielll** [comment]
It works perfectly, you can close this issue :+1:
