### ISSUE TITLE
editorconfig

### ISSUE THREAD

**Issue by lil5** [dom111/webdav-js#20]
https://editorconfig.org/

> EditorConfig helps developers define and maintain consistent coding styles between different editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles.

**Comment by lil5** [comment]
And IMHO tabs over spaces :1st_place_medal: 

http://lea.verou.me/2012/01/why-tabs-are-clearly-superior/

**Comment by dom111** [comment]
Hah, I'm a spaces person myself :P but perhaps that is having to adhere to others' coding standards for years! I'll certainly consider this though!
