### ISSUE TITLE
Make mobile friendly

### ISSUE THREAD

**Issue by lil5** [dom111/webdav-js#25]
- [x] A <meta tag for view port would help
- [x] A button to add files as drag doesn't work on mobile

**Comment by dom111** [comment]
I think adding a button for uploads is a great idea and something I did consider the other day!

I think mobile design is a great suggestion, and probably, the UI could do with an update either way, so something that scales well would be ideal!

**Comment by lil5** [comment]
Fixed #25.2 https://github.com/dom111/webdav-js/commit/48a8b7d06c533a7f0a0cb2342142dd6eab53e2dc#diff-1ad7ecb784ab7e0c330ecb8c28e6c149R443

**Comment by dom111** [comment]
Think we're all good now with both the checkbox items covered. I think mobile/responsive would be the first port of call for a redesign of this though.
