### ISSUE TITLE
Add additional test files to Docker environment

### ISSUE THREAD

**Issue by dom111** [dom111/webdav-js#28]
To test all file types, font, video, image, code.

I think ideally font, video, image items would be taken from the internet, rather than stored in the repo, code could come from the package itself.

**Comment by lil5** [comment]
Could use:

```
curl -o /path/out.ext httplocation
```

**Comment by dom111** [comment]
WIP: https://github.com/dom111/webdav-js/tree/master-topic-28-additional_test_files_in_docker

**Comment by dom111** [comment]
Fixed by #46.
