### ISSUE TITLE
CSS link broken

### ISSUE THREAD

**Issue by chrysn** [dom111/webdav-js#3]
The readme file's JS bookmark code says `..."https://cdn.rawgit.com/dom111/webdav-js/master/assets/css/style.min.css"...`, while the file in assets/css is named style-min.css.

As a result, practically no styling gets applied, and the result looks like "My Foldernamexmoverenamecopy". When the link is fixed manualy, everything looks nice.

**Comment by dom111** [comment]
[master cc52364] Fix error in README.md version of bookmarklet.
 1 file changed, 1 insertion(+), 1 deletion(-)

**Comment by dom111** [comment]
Thanks @chrysn! Fixed.
