### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by lil5** [dom111/webdav-js#30]
GLightbox does from what I can tell all the things featherlight does:
* https://glightbox.mcstudios.com.mx/
* https://github.com/mcstudios/glightbox

**Comment by dom111** [comment]
This is a good idea for sure and would reduce the overhead. jQuery is used extensively in the main module so it'd be worthwhile rewriting that functionality as well for sure!

**Comment by dom111** [comment]
I've updated this to be just remove jQuery dependency.

The comment about gLightbox is a useful jump-off point to save rebuilding lightbox functionality!

**Comment by chrysn** [comment]
Is there a short bookmarks-bar-style JS snippet with which I could test this branch? The README of feature/30-remove-jquery-dependency still imports jQuery.

**Comment by dom111** [comment]
> Is there a short bookmarks-bar-style JS snippet with which I could test this branch?

I'm afraid I'm still not much closer to that point, but I've re-worked this under a new branch of feature/convert-to-modules (which forked from feature/30-remove-jquery-dependency. I'm not sure when I'll have time to work on this again, but as soon as there's a testable version, I'll update here.

Thanks for your interest!

**Comment by dom111** [comment]
@chrysn I've got an updated version that is hopefully working with most functionality. I've not tested hugely, but I think I've got it working on the basics:

```javascript:["https://cdn.jsdelivr.net/gh/dom111/webdav-js@feature%2Fconvert-to-modules/assets/css/style-min.css","https://cdn.jsdelivr.net/gh/dom111/webdav-js@feature%2Fconvert-to-modules/src/webdav-min.js"].forEach((function(e,t){/css$/.test(e)?((t=document.createElement("link")).href=e,t.rel="stylesheet"):(t=document.createElement("script")).src=e,document.head.appendChild(t)}));```

**Comment by chrysn** [comment]
Thanks! I've tested it on viewing only (my WebDAV server is read-only), but there it rendered all directory listings well, including a bunch of exotic character cases.

**Comment by dom111** [comment]
Hey @chrysn, I've made a few more changes (quite a few actually!) it should properly handle errors now and let you know what was wrong. If you have time to test, that would be great!

```javascript:["https://cdn.jsdelivr.net/gh/dom111/webdav-js@feature/convert-to-modules/assets/css/style-min.css","https://cdn.jsdelivr.net/gh/dom111/webdav-js@feature/convert-to-modules/src/webdav-min.js"].forEach((function(e,s){/css$/.test(e)?((s=document.createElement("link")).href=e,s.rel="stylesheet"):(s=document.createElement("script")).src=e,document.head.appendChild(s)}));```

**Comment by dom111** [comment]
Fixed in v2.0.0!
