### ISSUE TITLE
Percent encoding in folder names

### ISSUE THREAD

**Issue by chrysn** [dom111/webdav-js#4]
When listing the contents of a folder with files containing whitespace or other characters, percent-encoded names are shown.

This is probably because the links (eg. `<D:href>http://.../Some%20Name/</D:href>`) are are taken literally and shown as a link to `Some%20Name` rather than `Some Name`. Unless there is a better indication, I think it makes that file and folder names, when prepared for display, are percent-decoded and interpreted as UTF-8, or possibly using the encoding of the HTML file.

I tested this with files served by lighttpd which sends no displayname; I did not test this with a WebDAV server that does send a displayname. (Mainly because nginx, which is the server I know to do that, has a [bug](https://github.com/arut/nginx-dav-ext-module/pull/15) that would cause the exactly same error on its own).

**Comment by dom111** [comment]
A very good point indeed! This is something I had noticed when using this but hadn't used any really complex Unicode names. Using Emoji or other similar high unicode characters, this is much more of a problem.

I'm just testing an implementation that utilises `decodeURIComponent` for the titles, will commit once I've tested.

**Comment by dom111** [comment]
@chrysn This should be good now, I've tested with emoji in filenames and spaces and `decodeURIComponent` has worked in my tests, please re-open if you spot any more issues. Thanks!
