### ISSUE TITLE
Upload event freezes browser for some time

### ISSUE THREAD

**Issue by chrysn** [dom111/webdav-js#5]
Uploading a ca. 10MB file per drag-and-drop freezes the browser (Firefox 61) for several seconds, to the point when the yellow "A page is slowing down..." bar appears on top.

I'm not experienced in JavaScript debugging, but what I think I found is that the frame rate drops to zero during the load DOM event, and lots of time are spent continuously in the sendAsBinary function. If that processing is actually necessary, maybe it can be moved out to where it does not freeze the UI any more?

**Comment by dom111** [comment]
After a discussion with a colleague about this, it appears that [`sendAsBinary` is obselete](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/sendAsBinary) so replacing this (and removing the polyfill) might well speed things up. I'll have a quick go at this...

**Comment by dom111** [comment]
Fixed in #9, tagged the wrong issue in commit message...
