### ISSUE TITLE
Add translations for all static text

### ISSUE THREAD

**Issue by dom111** [dom111/webdav-js#67]

**Comment by dom111** [comment]
**Text to be translated**:

- Drop files anywhere to upload
- Upload files
- or
- create a new directory
- Delete
- Rename
- Download
- Are you sure you want to delete '%s'?

**Comment by dom111** [comment]
There's also the pangram and alphabets used to demo fonts, not sure if there's benefit to making that localised or not though...

**Comment by nielll** [comment]
Dom, you are doing great job here, thank you very much.  :+1: 

In German:

- Datei/en hineinverschieben um sie hochzuladen
- Datei/en hochladen
- oder
- Neuen Ordner erstellen
- löschen
- umbenennen
- herunterladen
- Willst du wirklich die Datei '%s' löschen?
- Die Datei '%s' existiert bereits, willst du sie überschreiben?
- %s %s fehlgeschlagen: %s (%s)
- ' %s' wurde erfolgreich hochgeladen.
- '%s' wurde erfolgreich umbenannt in '%s'.
- '%s' wurde erfolgreich verschoben nach '%s'.
- '%s' wurde gelöscht.
- '%s' wurde erstellt.

In Portuguese:

- Mova o(s) arquivo(s) interno(s) para carregá-los
- Carregar arquivo(s)
- ou
- Criar uma nova pasta
- eliminar
- renomear
- descarregar
- Quer mesmo apagar o arquivo "%s"?
- O arquivo "%s" já existe, você quer sobrescrevê-lo?
- %s %s falhou: %s (%s)
- "%s" foi carregada com êxito.
- "%s" foi alterado para "%s" com êxito.
- "%s" foi transferida com êxito para "%s".
- "%s" foi suprimido.
- "%s" foi criada.

**Comment by chrysn** [comment]
For the pangram, "Franz jagt im komplett verwahrlosten Taxi quer durch Bayern" is commonly used in German if you do want to translate it. ([German Wikipedia](https://de.wikipedia.org/wiki/Pangramm) has a list for several other languages as well.)

The single "or" sounds a bit weird to be translated -- from last time I prepared strings for translation, I remember the recommendation to be to have the complete sentence translated, and rather have internal markup for interactive elements. That would help translators do capitalization right, or make adjustments if a particular sequence doesn't work too well.

**Comment by dom111** [comment]
@chrysn I also Googled a few pangrams and got: `„Fix, Schwyz!“, quäkt Jürgen blöd vom Paß.` for German and `Luís argüia à Júlia que «brações, fé, chá, óxido, pôr, zângão» eram palavras do português.` for Portuguese!

On the `or` I did consider dropping it, since it works well in English but doesn't lend itself so well in other languages as a construct at all. Using placeholders is definitely the approach I'd use in my day job so I'm not sure why I didn't take that approach here... ;)

**Comment by dom111** [comment]
This first attempt is going to be merged in #109.
