### ISSUE TITLE
How to specify the webdav server

### ISSUE THREAD

**Issue by rovitotv** [dom111/webdav-js#77]
I already have a webdav server running.....and I can't figure out how to specify the url, username, and password.  My javascript skills are not very good so any help you can offer would be appreciated.  Thanks!

**Comment by nielll** [comment]
Hi, you do not need to specify anything. Point with your Browser to the webdav URL and log in. After you provided the correct credentials, you will See the 403 error page. Then, click on the bookmarklet in your Bookmark tab (Code is in the readme) and there you go.

**Comment by nielll** [comment]
Hi, you do not need to specify anything. Point with your Browser to the webdav URL and log in. After you provided the correct credentials, you will See the 403 error page. Then, click on the bookmarklet in your Bookmark tab (Code is in the readme) and there you go.

**Comment by rovitotv** [comment]
Thank you so much for the quick response!  That does seem to work.  I am using [wsgidav](https://github.com/mar10/wsgidav) for my webdav server.  Now when I go to my webdav link I see both the regular wsgidav at the top and the webdav-js at the bottom.  It does work I will just have to think about integration.

**Comment by rovitotv** [comment]
Attached is a screen shot when logging into the webdav server then running the bookmarklet.  I might be able to modify wsgidav to include webdav-js at the bottom?  Any recommendations for integration of webdav-js with wsgidav?   Again thank you for the help! 

![webdav-js-screen](https://user-images.githubusercontent.com/1051881/97806674-e7514800-1c2a-11eb-8f6a-89ccbb6ebc2c.png)

**Comment by nielll** [comment]
Probably you can somewhere modify the template file and include this:

```js
<script type="text/javascript">["https://cdn.jsdelivr.net/gh/dom111/webdav-js/assets/css/style-min.css","https://cdn.jsdelivr.net/gh/dom111/webdav-js/src/webdav-min.js"].forEach((function(e,s){/css$/.test(e)?((s=document.createElement("link")).href=e,s.rel="stylesheet"):(s=document.createElement("script")).src=e,document.head.appendChild(s)}));
</script>
```

But I do not know the wsgidav davserver exactly. Or you just use webdav-js along with apache2. There is a sample config here: [apache-directory-list](https://github.com/dom111/webdav-js/tree/master/examples/apache-directory-list)

**Comment by dom111** [comment]
Thanks for your help here @nielll!

@rovitotv I've created [a PR for wsgidav to suggest a workaround for this](https://github.com/mar10/wsgidav/pull/192) so that it should be possible [to use this branch](https://github.com/dom111/webdav-js/tree/feature/wsgidav-example) if/when the PR is merged.

Hope this helps somewhat. In the interim, it should be possible to modify the bookmarklet to clear the page content with `document.body.innerHTML='';` between the `javascript:` and the rest of the bookmarklet.

**Comment by rovitotv** [comment]
Thank you @nielll and @dom111 this looks great....I will try this out ASAP.
