### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by lil5** [dom111/webdav-js#8]
https://choosealicense.com/

**Comment by dom111** [comment]
Hey there,

Thanks for your interest!

Thinking about maybe the MIT license?

I'll try and get this added when I next have the time!

Thanks!

Dom

**Comment by dom111** [comment]
Tagged the wrong issue in my branch, this commit actually fixed #5!

**Comment by lil5** [comment]
MIT is great, go for it :+1:

**Comment by lil5** [comment]
If you want you could add it using github with a click of a button

> https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by dom111** [comment]
Doing this through the interface was really easy, thanks!
