### ISSUE TITLE
Convert to TypeScript and replace webpack with esbuild

### ISSUE THREAD

**Issue by dom111** [dom111/webdav-js#98]

**Comment by jimmywarting** [comment]
https://jimmywarting.github.io/you-might-not-need-typescript/

**Comment by dom111** [comment]
@jimmywarting I think those are all fair points, but in this case I'm already bundling and utilising rebuild the process is practically instantaneous. I think as well, using TypeScript over Babel for backwards compatibility is preferable too, but I guess that's just a matter of preference! Thanks for sharing though!

**Comment by dom111** [comment]
Had a look at this in https://github.com/dom111/webdav-js/tree/switch-to-esbuild

Need to look at the tests though

**Comment by dom111** [comment]
This is addressed in #109.
